CREATE TABLE IF NOT EXISTS statistics (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 app VARCHAR(100) NOT NULL,
 uri VARCHAR(200) NOT NULL,
 ip VARCHAR(30) NOT NULL,
 timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);